//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoTable
    {
        public int TodoId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
